-- =============================================================================
-- Migration 001: PostGIS Geospatial Layer for RAITO
-- Run once on raito-db (Cloud SQL PostgreSQL 15, me-west1)
-- =============================================================================
-- Prerequisites: None. PostGIS is a trusted extension on Cloud SQL PostgreSQL.
-- The CREATE EXTENSION commands below handle everything (no database flags needed).
-- Executed successfully on 29 Mar 2026 via Cloud SQL Studio.
-- =============================================================================

-- Step 1: Enable PostGIS extension
-- Note: On Cloud SQL PostgreSQL, PostGIS is a trusted extension.
-- No need for the cloudsql.enable_postgis flag — just run CREATE EXTENSION.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

-- Verify
SELECT PostGIS_Version();


-- =============================================================================
-- Step 2: Add geospatial columns to master_data (Points of Sale)
-- =============================================================================

-- Add lat/lng floats for raw geocoder output (always store the raw values)
ALTER TABLE master_data
    ADD COLUMN IF NOT EXISTS latitude         DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude        DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS geo_confidence   VARCHAR(20),   -- 'ROOFTOP','RANGE_INTERPOLATED','GEOMETRIC_CENTER','APPROXIMATE'
    ADD COLUMN IF NOT EXISTS geo_status       VARCHAR(30),   -- 'OK','ZERO_RESULTS','PENDING','MANUAL_OVERRIDE'
    ADD COLUMN IF NOT EXISTS geo_formatted_address TEXT,     -- full address returned by Geocoding API
    ADD COLUMN IF NOT EXISTS geo_municipality VARCHAR(100),  -- parsed city/council name (EN)
    ADD COLUMN IF NOT EXISTS geo_municipality_he VARCHAR(100), -- parsed city/council name (HE)
    ADD COLUMN IF NOT EXISTS geo_geocoded_at  TIMESTAMPTZ,   -- when geocoding ran
    ADD COLUMN IF NOT EXISTS geo_point        GEOMETRY(Point, 4326); -- PostGIS point (WGS84)

-- Spatial index on the geometry column (critical for boundary queries)
CREATE INDEX IF NOT EXISTS idx_master_data_geo_point
    ON master_data USING GIST (geo_point);

-- Standard index on municipality for GROUP BY queries
CREATE INDEX IF NOT EXISTS idx_master_data_municipality
    ON master_data (geo_municipality);

-- Standard index on geo_status for filtering ungeocoded records
CREATE INDEX IF NOT EXISTS idx_master_data_geo_status
    ON master_data (geo_status);


-- =============================================================================
-- Step 3: Create municipalities_geo table to store GeoJSON boundaries
-- =============================================================================

CREATE TABLE IF NOT EXISTS municipalities_geo (
    id                SERIAL PRIMARY KEY,
    municipality_id   VARCHAR(50) UNIQUE NOT NULL,  -- geoBoundaries shapeID or CBS city code
    name_he           VARCHAR(100) NOT NULL,
    name_en           VARCHAR(100),
    region            VARCHAR(50),                  -- district (מחוז)
    geom              GEOMETRY(MultiPolygon, 4326) NOT NULL,
    population        INTEGER,
    area_km2          NUMERIC(10, 2),
    created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_municipalities_geo_geom
    ON municipalities_geo USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_municipalities_geo_name_en
    ON municipalities_geo (name_en);

CREATE INDEX IF NOT EXISTS idx_municipalities_geo_name_he
    ON municipalities_geo (name_he);


-- =============================================================================
-- Step 4: Create geo_kpi_cache table (pre-aggregated for fast map rendering)
-- Regenerated by the Geo Aggregator job after each data ingestion.
-- =============================================================================

CREATE TABLE IF NOT EXISTS geo_kpi_cache (
    id                   SERIAL PRIMARY KEY,
    municipality_id      VARCHAR(50) NOT NULL REFERENCES municipalities_geo(municipality_id),
    week_label           VARCHAR(10),          -- 'W13' or NULL for all-time
    kpi_revenue_ils      NUMERIC(12, 2) DEFAULT 0,
    kpi_units_sold       INTEGER DEFAULT 0,
    kpi_pos_count        INTEGER DEFAULT 0,    -- active POS in municipality
    kpi_avg_price        NUMERIC(8, 2),
    distributor          VARCHAR(30),          -- 'all' | 'icedream' | 'mayyan' | 'biscotti'
    computed_at          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (municipality_id, week_label, distributor)
);

CREATE INDEX IF NOT EXISTS idx_geo_kpi_municipality
    ON geo_kpi_cache (municipality_id);

CREATE INDEX IF NOT EXISTS idx_geo_kpi_week
    ON geo_kpi_cache (week_label);


-- =============================================================================
-- Step 5: Trigger to keep geo_point in sync with lat/lng
-- =============================================================================

CREATE OR REPLACE FUNCTION sync_geo_point()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
        NEW.geo_point = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326);
    ELSE
        NEW.geo_point = NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_geo_point ON master_data;
CREATE TRIGGER trg_sync_geo_point
    BEFORE INSERT OR UPDATE OF latitude, longitude ON master_data
    FOR EACH ROW EXECUTE FUNCTION sync_geo_point();


-- =============================================================================
-- Step 6: Useful views
-- =============================================================================

-- View: POS with sales, joined to municipality
-- Actual schema: master_data.entity (text) = POS identifier, linked to
-- sale_points.id via entity = id::text. Distributor name from distributors.name_en.
-- sales_transactions joins via sale_point_id. Week is week_number (smallint).
CREATE OR REPLACE VIEW v_pos_geo_summary AS
SELECT
    sp.id AS sale_point_id,
    sp.branch_name_he AS pos_name,
    d.name_en AS distributor,
    md.geo_municipality,
    md.geo_municipality_he,
    md.latitude,
    md.longitude,
    md.geo_confidence,
    md.geo_status,
    COALESCE(SUM(st.revenue_ils), 0)  AS total_revenue,
    COALESCE(SUM(st.units_sold), 0)   AS total_units,
    COUNT(DISTINCT st.week_number)    AS weeks_active
FROM sale_points sp
LEFT JOIN master_data md ON md.entity = sp.id::text
LEFT JOIN distributors d ON d.id = sp.distributor_id
LEFT JOIN sales_transactions st ON st.sale_point_id = sp.id
WHERE md.geo_status = 'OK'
GROUP BY sp.id, sp.branch_name_he, d.name_en,
         md.geo_municipality, md.geo_municipality_he,
         md.latitude, md.longitude, md.geo_confidence, md.geo_status;


-- View: Municipality KPI rollup (all-time, all distributors)
CREATE OR REPLACE VIEW v_municipality_kpi AS
SELECT
    mg.municipality_id,
    mg.name_he,
    mg.name_en,
    mg.region,
    COALESCE(SUM(st.revenue_ils), 0)  AS total_revenue,
    COALESCE(SUM(st.units_sold), 0)   AS total_units,
    COUNT(DISTINCT sp.id)             AS pos_count
FROM municipalities_geo mg
LEFT JOIN master_data md
    ON md.geo_municipality = mg.name_en
    AND md.geo_status = 'OK'
LEFT JOIN sale_points sp ON sp.id::text = md.entity
LEFT JOIN sales_transactions st ON st.sale_point_id = sp.id
GROUP BY mg.municipality_id, mg.name_he, mg.name_en, mg.region;


-- =============================================================================
-- Step 7: Queries used by the API (documented here for reference)
-- =============================================================================

-- Q1: Choropleth data — aggregate KPI by municipality for a given week + distributor
-- Used by: GET /api/geo/choropleth?week=W13&distributor=all&kpi=revenue
-- Actual schema: sale_points → sales_transactions via sale_point_id,
-- master_data.entity = sale_points.id::text, distributors.name_en for name
/*
SELECT
    mg.municipality_id,
    mg.name_en,
    mg.name_he,
    COALESCE(SUM(st.revenue_ils), 0)  AS revenue_ils,
    COALESCE(SUM(st.units_sold), 0)   AS units_sold,
    COUNT(DISTINCT sp.id)             AS pos_count
FROM municipalities_geo mg
LEFT JOIN master_data md
    ON md.geo_municipality = mg.name_en
    AND md.geo_status = 'OK'
LEFT JOIN sale_points sp ON sp.id::text = md.entity
LEFT JOIN distributors d ON d.id = sp.distributor_id
LEFT JOIN sales_transactions st
    ON st.sale_point_id = sp.id
    AND (:week = 'all' OR st.week_number = :week::smallint)
    AND (:distributor = 'all' OR d.key = :distributor)
GROUP BY mg.municipality_id, mg.name_en, mg.name_he
ORDER BY revenue_ils DESC;
*/

-- Q2: Drill-down — POS within a specific municipality
-- Used by: GET /api/geo/pos?municipality_id=5000&week=W13
/*
SELECT
    sp.id AS sale_point_id,
    sp.branch_name_he AS pos_name,
    md.latitude,
    md.longitude,
    d.name_en AS distributor,
    COALESCE(SUM(st.revenue_ils), 0) AS revenue_ils,
    COALESCE(SUM(st.units_sold), 0)  AS units_sold
FROM sale_points sp
LEFT JOIN master_data md ON md.entity = sp.id::text
LEFT JOIN distributors d ON d.id = sp.distributor_id
LEFT JOIN sales_transactions st
    ON st.sale_point_id = sp.id
    AND (:week = 'all' OR st.week_number = :week::smallint)
JOIN municipalities_geo mg
    ON md.geo_municipality = mg.name_en
    AND mg.municipality_id = :municipality_id
WHERE md.geo_status = 'OK'
  AND md.latitude IS NOT NULL
GROUP BY sp.id, sp.branch_name_he, md.latitude, md.longitude, d.name_en
ORDER BY revenue_ils DESC;
*/

-- Q3: Spatial drill-down (using PostGIS boundary — more precise than name match)
-- Used when municipality_id maps to a polygon in municipalities_geo
/*
SELECT
    sp.id AS sale_point_id,
    sp.branch_name_he AS pos_name,
    md.latitude,
    md.longitude,
    d.name_en AS distributor,
    COALESCE(SUM(st.revenue_ils), 0) AS revenue_ils,
    COALESCE(SUM(st.units_sold), 0)  AS units_sold
FROM sale_points sp
LEFT JOIN master_data md ON md.entity = sp.id::text
LEFT JOIN distributors d ON d.id = sp.distributor_id
LEFT JOIN sales_transactions st ON st.sale_point_id = sp.id
    AND (:week = 'all' OR st.week_number = :week::smallint)
WHERE md.geo_status = 'OK'
  AND ST_Within(
        md.geo_point,
        (SELECT geom FROM municipalities_geo WHERE municipality_id = :municipality_id)
      )
GROUP BY sp.id, sp.branch_name_he, md.latitude, md.longitude, d.name_en;
*/
